# generated by datamodel-codegen:
#   filename:  tensorforge-phase2-openapi-v2.yaml
#   timestamp: 2026-10-08T03:55:04+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, confloat, constr


class Channel(StrEnum):
    email = 'email'
    chat = 'chat'
    call_transcript = 'call_transcript'


class Category(StrEnum):
    payment_refund = 'payment_refund'
    ride_trip_issue = 'ride_trip_issue'
    lost_item = 'lost_item'
    order_missing_wrong = 'order_missing_wrong'
    delivery_delay = 'delivery_delay'
    food_quality = 'food_quality'
    account_promo = 'account_promo'
    safety_conduct = 'safety_conduct'
    app_technical = 'app_technical'
    general_inquiry = 'general_inquiry'
    spam_irrelevant = 'spam_irrelevant'


class Team(StrEnum):
    Payments___Refunds = 'Payments & Refunds'
    Ride_Operations = 'Ride Operations'
    Lost___Found = 'Lost & Found'
    Food_Operations = 'Food Operations'
    Delivery_Operations = 'Delivery Operations'
    Restaurant_Quality = 'Restaurant Quality'
    Account_Services = 'Account Services'
    Trust___Safety = 'Trust & Safety'
    Tech_Support = 'Tech Support'
    Front_line_Support = 'Front-line Support'
    Auto_close___Spam_Filter = 'Auto-close / Spam Filter'


class PredictRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ticket_id: constr(max_length=64) | None = Field(
        None,
        description='Optional identifier for `/predict` (required for `/predict/batch` and `/batch/jobs`). If provided, echo\nit back in the response. Do not use it as a model feature (IDs carry no signal and the\nharness uses opaque values).\n',
        examples=['TF-TE-000001'],
    )
    channel: Channel
    subject: constr(max_length=500) | None = Field(
        '',
        description='Email subject line. Empty string or omitted for chat and call transcripts.',
    )
    text: constr(pattern=r'\S', min_length=1, max_length=10000) = Field(
        ...,
        description='Ticket body, chat messages joined by newlines, or the call transcript. UTF-8.\nMust contain at least one non-whitespace character, otherwise return `422`.\nEmoji-only and mixed-script text is valid.\n',
    )


class PredictResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ticket_id: str | None = Field(
        None, description='Echoed from the request when provided.'
    )
    category: Category
    secondary_category: Category | None = Field(
        ...,
        description='Second issue if the ticket clearly contains two, otherwise `null`. Must differ from\n`category`. The key must always be present, with value `null` when there is none.\n',
    )
    team: Team
    is_urgent: bool = Field(
        ..., description='Whether the ticket needs immediate human attention.'
    )
    confidence: confloat(ge=0.0, le=1.0) = Field(
        ...,
        description='Confidence in the **primary** `category`, between 0 and 1. Used for calibration and\nabstention scoring, so it should reflect real uncertainty. Ambiguous and noisy\ntickets should receive lower values.\n',
    )
    model_version: constr(min_length=1) = Field(
        ...,
        description="Version of the model that produced the prediction. Must match a versioned artifact\nin the team's repository (for example a registry tag or file hash). Must be identical\nacross `/health`, `/predict` and `/predict/batch` for a given deployment.\n",
        examples=['v1.2'],
    )
    needs_human_review: bool | None = Field(
        None,
        description='Optional bonus field. `true` when the system would send the ticket to a human triage\nqueue instead of auto-routing it (for example, confidence below a chosen threshold).\nTeams that use it should explain the threshold in the README.\n',
    )


class BatchRequest(BaseModel):
    tickets: list[PredictRequest] = Field(
        ...,
        description='Tickets to classify. `ticket_id` values must be unique within the array.',
        max_length=100,
        min_length=1,
    )


class Meta(BaseModel):
    count: int | None = Field(
        None,
        description='Number of predictions returned. Must equal the number of tickets sent.',
    )
    model_version: str | None = None
    processing_time_ms: int | None = None


class BatchResponse(BaseModel):
    predictions: list[PredictResponse] = Field(
        ..., description='One prediction per request item, in the same order.'
    )
    meta: Meta | None = Field(
        None, description='Optional batch-level information. Ignored by the scorer.'
    )


class BatchJobRequest(BaseModel):
    tickets: list[PredictRequest] = Field(
        ...,
        description='Tickets to classify. `ticket_id` values must be unique within the array.',
        max_length=5000,
        min_length=1,
    )


class Status(StrEnum):
    queued = 'queued'
    running = 'running'
    succeeded = 'succeeded'
    failed = 'failed'
    cancelled = 'cancelled'


class Error(BaseModel):
    code: str = Field(..., examples=['interrupted'])
    message: str


class BatchJobStatus(BaseModel):
    job_id: str
    status: Status
    total: int = Field(..., description='Number of tickets in the job.')
    processed: int = Field(
        ..., description='Number of tickets classified so far. Never decreases.'
    )
    created_at: AwareDatetime | None = None
    started_at: AwareDatetime | None = None
    finished_at: AwareDatetime | None = Field(
        None,
        description='Set when the job reaches `succeeded`, `failed` or `cancelled`.',
    )
    expires_at: AwareDatetime | None = Field(
        None,
        description='When results will be discarded. Set once the job finishes; at least 6 hours later.',
    )
    model_version: str | None = None
    error: Error | None = Field(
        None, description='Present only when `status` is `failed`.'
    )


class Status1(StrEnum):
    succeeded = 'succeeded'


class BatchJobResults(BaseModel):
    job_id: str
    status: Status1
    total: int = Field(
        ..., description='Total predictions in the job (not just this page).'
    )
    offset: int
    limit: int
    next_offset: int | None = Field(
        ...,
        description='Offset to request for the next page, or `null` if this is the last page.',
    )
    model_version: str | None = None
    predictions: list[PredictResponse] = Field(
        ..., description='Predictions in the same order as the submitted tickets.'
    )


class Status2(StrEnum):
    ok = 'ok'
    loading = 'loading'


class HealthResponse(BaseModel):
    status: Status2
    model_version: str | None = Field(
        ..., description='Loaded model version, or `null` while loading.'
    )
    model_loaded: bool | None = Field(
        None, description='Optional. `true` once the model is ready.'
    )


class Detail(BaseModel):
    index: int | None = Field(
        None,
        description='Zero-based index of the failing item in `tickets` (batch requests only).',
        examples=[3],
    )
    field: str | None = Field(None, examples=['text'])
    issue: str | None = Field(None, examples=['must not be empty'])


class Error1(BaseModel):
    code: str = Field(
        ..., description='Short machine-readable code.', examples=['validation_error']
    )
    message: str = Field(
        ...,
        description='Human-readable explanation. Do not include stack traces.',
        examples=["Field 'text' must contain at least one non-whitespace character."],
    )
    details: list[Detail] | None = Field(
        None, description='Optional list of field-level problems.'
    )


class ErrorResponse(BaseModel):
    error: Error1
